from PyQt6 import QtCore, QtGui, QtWidgets
import socket
import numpy as np
import time
def randomEnv():
    #seed=np.random.randint(1,101)
    #np.random.seed(seed)
    tep=str(np.random.randint(-20,41))
    light=str(np.random.randint(300,501))
    wet=str(np.random.randint(0,101))
    return tep,light,wet
class UdpClient(QtCore.QThread):
    message_res=QtCore.pyqtSignal(str)
    message_data=QtCore.pyqtSignal(tuple)
    socket=None
    def __init__(self):
        super().__init__()
        self.socket=socket.socket(socket.AF_INET,socket.SOCK_DGRAM)
    def __del__(self):
        self.wait()
    def run(self):
        while True:
            self.LocalHost="127.0.0.1"
            self.id="1"
            data=list(randomEnv())
            tep=data[0]
            light=data[1]
            wet=data[2]
            #self.message.emit(f"Temperature: {tep}, Light: {light}, Wet: {wet}")
            self.socket.sendto(tep.encode('utf-8'),(self.LocalHost,8080))
            self.socket.sendto(light.encode('utf-8'),(self.LocalHost,8080))
            self.socket.sendto(wet.encode('utf-8'),(self.LocalHost,8080))
            self.socket.sendto(self.id.encode('utf-8'),(self.LocalHost,8080))
            self.status,_=self.socket.recvfrom(1024)
            self.data_id,_=self.socket.recvfrom(1024)
            data.append(self.data_id.decode('utf-8'))
            data=tuple(data)
            self.message_data.emit(data)
            if self.status==b"1":
                self.message_res.emit("open")
            else:
                self.message_res.emit("close")
            time.sleep(1000)
            #print(tep,light,wet)
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Ludeng_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Ludeng_label.setGeometry(QtCore.QRect(90, 110, 170, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Ludeng_label.setFont(font)
        self.Ludeng_label.setObjectName("Ludeng_label")
        self.Huanjin_label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Huanjin_label_2.setGeometry(QtCore.QRect(90, 180, 170, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Huanjin_label_2.setFont(font)
        self.Huanjin_label_2.setObjectName("Huanjin_label_2")
        self.Tem_label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Tem_label_3.setGeometry(QtCore.QRect(190, 280, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Tem_label_3.setFont(font)
        self.Tem_label_3.setObjectName("Tem_label_3")
        self.Wet_label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Wet_label_4.setGeometry(QtCore.QRect(190, 330, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Wet_label_4.setFont(font)
        self.Wet_label_4.setObjectName("Wet_label_4")
        self.Light_label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Light_label_5.setGeometry(QtCore.QRect(190, 380, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Light_label_5.setFont(font)
        self.Light_label_5.setObjectName("Light_label_5")
        self.pushButton_ON = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_ON.setGeometry(QtCore.QRect(640, 130, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_ON.setFont(font)
        self.pushButton_ON.setObjectName("pushButton_ON")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 280, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 330, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 380, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.is_ON = QtWidgets.QLabel(parent=self.centralwidget)
        self.is_ON.setGeometry(QtCore.QRect(280, 110, 170, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.is_ON.setFont(font)
        self.is_ON.setObjectName("is_ON")
        self.pushButton_OUT = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_OUT.setGeometry(QtCore.QRect(640, 290, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_OUT.setFont(font)
        self.pushButton_OUT.setObjectName("pushButton_OUT")
        self.label_f_isON = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_f_isON.setGeometry(QtCore.QRect(660, 80, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_f_isON.setFont(font)
        self.label_f_isON.setObjectName("label_f_isON")
        self.label_f = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_f.setGeometry(QtCore.QRect(590, 30, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setUnderline(False)
        self.label_f.setFont(font)
        self.label_f.setObjectName("label_f")
        self.label_ipad = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_ipad.setGeometry(QtCore.QRect(20, 520, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_ipad.setFont(font)
        self.label_ipad.setObjectName("label_ipad")
        self.label_ip = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_ip.setGeometry(QtCore.QRect(120, 520, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_ip.setFont(font)
        self.label_ip.setText("")
        self.label_ip.setObjectName("label_ip")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Ludeng_label.setText(_translate("MainWindow", "路灯状态:"))
        self.Huanjin_label_2.setText(_translate("MainWindow", "环境状态:"))
        self.Tem_label_3.setText(_translate("MainWindow", "温度:"))
        self.Wet_label_4.setText(_translate("MainWindow", "湿度:"))
        self.Light_label_5.setText(_translate("MainWindow", "亮度:"))
        self.pushButton_ON.setText(_translate("MainWindow", "开启"))
        self.label.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "0"))
        self.is_ON.setText(_translate("MainWindow", "关闭"))
        self.pushButton_OUT.setText(_translate("MainWindow", "关闭"))
        self.label_f_isON.setText(_translate("MainWindow", "关闭"))
        self.label_f.setText(_translate("MainWindow", "设备状态:"))
        self.label_ipad.setText(_translate("MainWindow", "设备ID:"))
        self.socketThread=None
        self.pushButton_ON.clicked.connect(self.start)
        self.pushButton_OUT.clicked.connect(self.end)
    def end(self):
        if (self.label_f_isON.text()=="关闭"):
            return
        else:
            if self.socketThread is not None:
                self.socketThread=None
                self.label_f_isON.setText("关闭")
                self.update_status('close')
                self.label.setText("")
                self.label_2.setText("")
                self.label_3.setText("")
    def start(self):
        if (self.label_f_isON.text()=="开启"):
            return
        else:
            self.label_f_isON.setText("开启")
            self.socketThread=UdpClient()
            self.socketThread.message_data.connect(self.display)
            self.socketThread.message_res.connect(self.update_status)
            self.socketThread.start()
    def display(self,data):
        self.label.setText(data[0]+"摄氏度")
        self.label_2.setText(data[1]+"勒克斯")
        self.label_3.setText(data[2]+"%")
        self.label_ip.setText(data[3])
    def update_status(self,status):
        self.is_ON.setText(status)
        if status=='open':
            self.is_ON.setStyleSheet("color:red")
        else:
            self.is_ON.setStyleSheet("color:black")
if __name__=="__main__":
    import sys
    app=QtWidgets.QApplication(sys.argv)
    MainWindow=QtWidgets.QMainWindow()
    ui=Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())